### ISSUE TITLE
app_review does not specify a Swift version

### ISSUE THREAD

**Issue by Arkangel12** [fluttercommunity/app_review#10]
After add it to pubspec and run the app the pod install send and error.

<img width="924" alt="Screen Shot 2019-10-09 at 8 57 53 AM" src="https://user-images.githubusercontent.com/29683014/66502897-05c22f80-ea7b-11e9-948f-7952a141412b.png">

I'm already having other pods installs like firebase and facebook but this one it get this error.

Let me know if  you need more details about this.

**Comment by philiplindberg** [comment]
I'm seeing the same thing.

Also tried adding `use_frameworks!` and `config.build_settings['SWIFT_VERSION'] = '5.0'` to the `target 'Runner'` block of my Podfile as detailed in [this SO](https://github.com/ko2ic/image_downloader/issues/9#issuecomment-471608482), with no luck.

**Comment by Jethro87** [comment]
Seeing the same issue.

```
[!] Unable to determine Swift version for the following pods:
    - `app_review` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

Here's what I'm running.
```
Flutter 1.10.7 • channel beta • https://github.com/flutter/flutter.git
Framework • revision e70236e36c (3 weeks ago) • 2019-10-02 09:32:30 -0700
Engine • revision 9e6314d348
Tools • Dart 2.6.0 (build 2.6.0-dev.0.0 1103600280)
```

**Comment by davidkneely** [comment]
Getting the same error here. Is there another version of the pod that we can use? 

> - `app_review` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by AndroidNils** [comment]
Same Problem: ```- `app_review` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.```

Any fixes for this?

**Comment by dkobia** [comment]
@Arkangel12 you probably want to make sure that your flutter app is set up for Swift.

If you not, you could probably fix it by running `flutter create -i swift .` in the root of your app.

**Comment by ejprok** [comment]
What worked for me was manually creating a Swift file in Xcode to create the objc bridging header.  Using `flutter create -i swift . `  did not work for me.  Messing with the Podfile did not help either.

**Comment by rodydavis** [comment]
is this still happening? I can try recreating the project with the latest Flutter version

**Comment by adim86** [comment]
Yes, this is still happening. I am unable to fix it

> is this still happening? I can try recreating the project with the latest Flutter version

**Comment by Noninus** [comment]
Yes, this is still happening. I am unable to fix it too. Can anyone help?

**Comment by Noninus** [comment]
I created a copy of this package and corrected it!

if anyone need now:

  app_review:
    git:
      url: https://github.com/Noninus/app_review2.git 

To correct it, need to add this line:

s.swift_version       = '4.0'

to app_review.podspec:

```
#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html
#
Pod::Spec.new do |s|
  s.name             = 'app_review'
  s.version          = '1.0.1'
  s.summary          = 'Request and Write Reviews and Open Store Listing for Android&#x2F;iOS in Flutter.'
  s.description      = <<-DESC
Request and Write Reviews and Open Store Listing for Android&#x2F;iOS in Flutter.
                       DESC
  s.homepage         = 'http://rodydavis.com'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Your Company' => 'email@example.com' }
  s.source           = { :path => '.' }
  s.swift_version       = '4.0'
  s.source_files = 'Classes/**/*'
  s.public_header_files = 'Classes/**/*.h'
  s.dependency 'Flutter'
  
  s.ios.deployment_target = '8.0'
end

```

**Comment by matitalatina** [comment]
I fixed following this comment.
https://github.com/ko2ic/image_downloader/issues/9#issuecomment-471608482

**Comment by rodydavis** [comment]
should be fixed on the latest version.
