### ISSUE TITLE
Sumbit is not working on ios

### ISSUE THREAD

**Issue by Madhav1022** [fluttercommunity/app_review#11]
I have a button to Rate and after that submit to the AppStore. It works in android but doesn't work in iOS. How can I solve this issue ?
![Skype_Picture_2019_10_24T05_48_51_897Z](https://user-images.githubusercontent.com/19186135/67458101-0ea72980-f655-11e9-88ed-2a4e2c33b341.jpeg)

**Comment by akalitenya** [comment]
Maybe it will work after you publish app to App Store and download it. It looks similar to https://github.com/Skyost/rate_my_app/issues/1

**Comment by rodydavis** [comment]
Test with your app in production, not TestFlight. Otherwise apple doesn't let you submit, only test
