### ISSUE TITLE
Example is broken

### ISSUE THREAD

**Issue by PauloKeller** [fluttercommunity/app_review#12]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Linux, locale en_US.UTF-8)
 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.35.1)
[✓] Connected device (1 available)

• No issues found!

Steps to reproduce: clone project > open example > run 

> [ +590 ms] /home/paulo/.gradle/caches/transforms-1/files-1.1/core-1.0.0.aar/a5f6e38458b0d939cde93a6fee2c4982/res/values/values.xml:133:5-70: AAPT: error: resource
> android:attr/fontVariationSettings not found.
> [   +2 ms] /home/paulo/.gradle/caches/transforms-1/files-1.1/core-1.0.0.aar/a5f6e38458b0d939cde93a6fee2c4982/res/values/values.xml:133:5-70: AAPT: error: resource android:attr/ttcIndex
> not found.
> [        ] /home/paulo/Workspace/app_review/example/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:87: error: resource
> android:attr/fontVariationSettings not found.
> [        ] /home/paulo/Workspace/app_review/example/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:87: error: resource android:attr/ttcIndex not
> found.
> [   +1 ms] error: failed linking references.
> [  +52 ms] Failed to execute aapt
> [   +1 ms] com.android.ide.common.process.ProcessException: Failed to execute aapt
> [        ]      at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:796)
> [        ]      at com.android.build.gradle.tasks.ProcessAndroidResources.invokeAaptForSplit(ProcessAndroidResources.java:551)
> [   +7 ms]      at com.android.build.gradle.tasks.ProcessAndroidResources.doFullTaskAction(ProcessAndroidResources.java:285)
> [        ]      at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:109)
> [        ]      at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
> [        ]      at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
> [        ]      at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
> [        ]      at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
> [        ]      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
> [        ]      at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
> [        ]      at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
> [        ]      at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
> [        ]      at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
> [        ]      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
> [   +5 ms]      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
> [        ]      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
> [        ]      at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
> [        ]      at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
> [        ]      at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
> [        ]      at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
> [        ]      at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
> [        ]      at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
> [        ]      at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
> [        ]      at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
> [        ]      at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
> [        ]      at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
> [        ]      at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
> [        ]      at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
> [        ]      at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
> [        ]      at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
> [        ]      at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
> [        ]      at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
> [        ]      at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
> [        ]      at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
> [        ]      at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
> [        ]      at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
> [        ]      at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
> [        ]      at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
> [        ]      at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
> [        ]      at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
> [        ]      at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
> [        ]      at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
> [        ] Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
> [  +13 ms]      at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:503)
> [        ]      at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:482)
> [   +1 ms]      at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
> [        ]      at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:794)
> [        ]      ... 41 more
> [        ] Caused by: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
> [        ]      at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:503)
> [        ]      at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:462)
> [        ]      at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
> [        ]      at com.android.builder.internal.aapt.v2.QueueableAapt2.lambda$makeValidatedPackage$1(QueueableAapt2.java:179)
> [        ] Caused by: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
> [        ]      at com.android.builder.png.AaptProcess$NotifierProcessOutput.handleOutput(AaptProcess.java:463)
> [        ]      at com.android.builder.png.AaptProcess$NotifierProcessOutput.err(AaptProcess.java:415)
> [        ]      at com.android.builder.png.AaptProcess$ProcessOutputFacade.err(AaptProcess.java:332)
> [        ]      at com.android.utils.GrabProcessOutput$1.run(GrabProcessOutput.java:104)
> [        ] FAILURE: Build failed with an exception.
> [        ] * What went wrong:
> [        ] Execution failed for task ':app:processDebugResources'.
> [        ] > Failed to execute aapt
> [        ] * Try:
> [        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> [        ] * Get more help at https://help.gradle.org
> [        ] BUILD FAILED in 9s
> [        ] 52 actionable tasks: 5 executed, 47 up-to-date
> [ +359 ms] Running Gradle task 'assembleDebug'... (completed in 9.6s)
> [        ] *******************************************************************************************
> [        ] The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
> [        ] See https://goo.gl/CP92wY for more information on the problem and how to fix it.
> [        ] *******************************************************************************************
> [   +4 ms] "flutter run" took 12,955ms.
> Gradle task assembleDebug failed with exit code 1
> 
> #0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
> #1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:751:5)
> #2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
> #3      _rootRunUnary (dart:async/zone.dart:1132:38)
> #4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
> #5      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
> #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
> #7      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
> #8      Future._completeWithValue (dart:async/future_impl.dart:522:5)
> #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
> #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
> #11     runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart)
> #12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
> #13     _rootRunUnary (dart:async/zone.dart:1132:38)
> #14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
> #15     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
> #16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
> #17     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
> #18     Future._completeWithValue (dart:async/future_impl.dart:522:5)
> #19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
> #20     _rootRun (dart:async/zone.dart:1124:13)
> #21     _CustomZone.run (dart:async/zone.dart:1021:19)
> #22     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
> #23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
> #24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> #25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
> #26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
> #27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
>

**Comment by rodydavis** [comment]
The app has to be in production for this to work. i.e. app that is published to the store and then try again
