### ISSUE TITLE
Lookup should include country code in the base lookup URL

### ISSUE THREAD

**Issue by shinsenter** [fluttercommunity/app_review#17]
Thank you for great package!

I'm trying to lookup my appId from `getiOSAppID` method, and it calls to: http://itunes.apple.com/lookup?bundleId=my.app.id.here

But the response always return
{
 "resultCount":0,
 "results": []
}

My app is ONLY available in Japan store, so the lookup should include country code in the base lookup URL:

http://itunes.apple.com/jp/lookup?bundleId=my.app.id.here

It would be great if I could add country code in to lookup URL, or change the base lookup URL.

**Comment by rodydavis** [comment]
I am open for PRs this would be a great addition! Let me know and i will publish an update.

**Comment by shinsenter** [comment]
@rodydavis 
This may be resolved with  #38.

**Comment by rodydavis** [comment]
Fixed on 2.0.0
