### ISSUE TITLE
What is the purpose of the call back ?

### ISSUE THREAD

**Issue by yelkamel** [fluttercommunity/app_review#18]
Hello 

I can I know the purpose of the call-back       
`AppReview.requestReview.then((onValue) {
        print(onValue);
      });`
regarding the iOS documentation, we dont have callback  of the rating review pop: 
https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview

thanks

**Comment by rodydavis** [comment]
Just a sanity check to make sure there were no errors. On android you could store a timestamp to know when to call again, on ios it doesnt really matter
