### ISSUE TITLE
Use method instead of getters

### ISSUE THREAD

**Issue by aloisdeniel** [fluttercommunity/app_review#19]
I would preferably used methods for instead of getters that returns a new `Future`.

I find it more clear that an action is triggered by calling a method in a fire and forget case. At first I thought that there were a cache of the `Future`.

```dart
AppReview.storeListing; // I would find `AppReview.storeListing()` more transparent on the fact that a processing is potentially triggered.
```

**Comment by rodydavis** [comment]
Yes i will refactor on a future update!

**Comment by shinsenter** [comment]
@aloisdeniel 
This may be resolved with No #38.

**Comment by tzachov** [comment]
As far as I see this issue was not resolved.
I agree with @aloisdeniel - getters for Futures feels unnatural.

I think all of these getters should be methods:
```dart
AppReview.isRequestReviewAvailable
AppReview.requestReview
AppReview.writeReview
AppReview.storeListing
AppReview.getAppID
AppReview.getiOSAppID
```

**Comment by rodydavis** [comment]
I'm open for PRs!
