### ISSUE TITLE
Folder docs is indexed by Intellij for ages

### ISSUE THREAD

**Issue by rostopira** [fluttercommunity/app_review#20]
I've updated to latest version from pub, and Intellij IDEA got stuck on indexing docs folder.
Most probably it's due to main.dart.js recognized as valuable source code.
I had to delete folder and restart to get it unstuck.

**Comment by rostopira** [comment]
To clarify, I'm using Intellij IDEA Ultimate, it may not be reproducible on CE, because it doesn't have JS support

**Comment by shi-rudo** [comment]
any updated on this?

**Comment by rodydavis** [comment]
Is this still an issue? I can delete the folder and have it on a separate branch for the demo
