### ISSUE TITLE
app_review canLaunch("market://") won't work correctly

### ISSUE THREAD

**Issue by T-mans** [fluttercommunity/app_review#24]
I have test on app_review 1.0.0
I found code in app_review.dart like below won't work fine  which will always lead android to open google play in browser.

> if (await canLaunch("market://")) {// this always return false
        print('launching store page');
        await launch("market://details?id=" + _appID);
        details = 'Launched App Store Directly: $_appID';
      } else {// so we always run in else,
        await launch("https://play.google.com/store/apps/details?id=" + _appID);
        details = 'Launched App Store: $_appID';
      }

I changed the url from `market://` to `market://details` which is used in brace, then it works fine.

And I find this keep the same in latest version of 1.1.0+1.

**Comment by rodydavis** [comment]
Please submit a PR and i will be happy to publish!

**Comment by maddyb99** [comment]
Is this issue solved or WIP?

**Comment by shinsenter** [comment]
@T-mans 
@maddyb99 
This may be resolved with No #38.
