### ISSUE TITLE
what is onValue?

### ISSUE THREAD

**Issue by shinriyo** [fluttercommunity/app_review#28]
Hello. Thank you for such good plugin.

I read the document.
`onValue` is the rate start number which user reviewed?

```
    if (Platform.isIOS) {
      AppReview.requestReview.then((onValue) {
        print(onValue);
      });
    }
```

Or, it is not. Could you tell me how to get the star count which user reviewed.

**Comment by rodydavis** [comment]
https://github.com/fluttercommunity/app_review/issues/18
