### ISSUE TITLE
Can developers configure default jump links？

### ISSUE THREAD

**Issue by a-href** [fluttercommunity/app_review#34]
![image](https://user-images.githubusercontent.com/13159272/86729984-a2dce380-c060-11ea-8220-4b35bdbd3f2a.png)

Like this,When I can't launch the market, I want to jump to another link.
So is it possible to configure this link for developers？

**Comment by Jaykong** [comment]
Is it ok we open a PR to support not only google play and so other android market?

**Comment by shinsenter** [comment]
@a-href 
@Jaykong 
This may be resolved with No #38.
