### ISSUE TITLE
Update .gitignore to ignore IDE and build related files

### ISSUE THREAD

**Issue by maddyb99** [fluttercommunity/app_review#35]
I came here to try to fix #24 but found out that the repository has alot of files from IDE and builds floating around. So I decided to help with that first.

I will open a PR for you to review!

**Comment by shinsenter** [comment]
@maddyb99 
This may be resolved with No #38.

**Comment by maddyb99** [comment]
@shinsenter I don't think this repository is maintained anymore.
Due to the lack of activity, I opened this basic PR and waited for a response before doing more stuff, and as you can see, there is no response.
