### ISSUE TITLE
Support Android's new In-App Review API

### ISSUE THREAD

**Issue by britannio** [fluttercommunity/app_review#37]
https://developer.android.com/guide/playcore/in-app-review
https://android-developers.googleblog.com/2020/08/in-app-review-api.html

**Comment by BansookNam** [comment]
as you can see in this article.
iOS Review count, usually a lot bigger than Android's review count.
https://www.androidpolice.com/2020/01/11/play-store-tests-include-new-in-app-review-dialogs-and-a-dedicated-reviews-section/

from play core 1.8.0 (release on july)
we can use this feature above 5.0.
https://developer.android.com/reference/com/google/android/play/core/release-notes

We'll very much appreciate if you guys support this feature.

**Comment by jonasbark** [comment]
Just created a PR with it 👍

**Comment by britannio** [comment]
Awesome, I was impatient yesterday and wanted to learn how to create a plugin so I created https://github.com/britannio/in_app_review

**Comment by rodydavis** [comment]
I'm open to PRs for it!

**Comment by britannio** [comment]
> I'm open to PRs for it!

https://github.com/fluttercommunity/app_review/pull/39 LGTM
