### ISSUE TITLE
Bug in v2.0.0

### ISSUE THREAD

**Issue by shinsenter** [fluttercommunity/app_review#41]
Some issues in fresh released v2.0.0:
- Duplicated code in utility files and main class
- Missing country code in `getIosAppId()` and `iosReviewUrlBase()`
- Android utility methods have not been implemented
- `AppReview.getBundleName()` always returns 'net.webike.app01' (I'm sorry, it is my mistake)

Issues may be solved with #40

**Comment by shinsenter** [comment]
@rodydavis 
Since there is a bug with v2.0.0, pls update to v2.0.1 asap.

**Comment by rodydavis** [comment]
👍🏼

**Comment by rodydavis** [comment]
Deployed
