### ISSUE TITLE
Does the library support "Google Play In-App Review API"?

### ISSUE THREAD

**Issue by dlpigpen** [fluttercommunity/app_review#46]
Recently Google released "Google Play In-App Review API". Basically it likes the same Store kit request review framework on iOS. I am not sure this feature has been integrated in our library. 

[](https://developer.android.com/guide/playcore/in-app-review)

**Comment by alectogeek** [comment]
Discussed in #37.
Yes, this library supports Google Play In-App Review API. But there is a problem described in #45. I'm not sure if the problem is also relevant for production apps. I decided to temporarily use this plugin: https://github.com/fluttercommunity/app_review

**Comment by dlpigpen** [comment]
@alectogeek al
 Thanks a lot for your support. Can I confirm the temporary link is https://github.com/britannio/in_app_review or https://github.com/fluttercommunity/app_review?

**Comment by alectogeek** [comment]
@dlpigpen oh, yea. The temporary link is https://github.com/britannio/in_app_review. I pasted the wrong link by accident :)

**Comment by dlpigpen** [comment]
@alectogeek  yeah, I think so. We can close this question at this time. 
Thanks so much for your contribution to the Flutter community.
