### ISSUE TITLE
What is onValue? (while being mentioned in the readme there was no explanation)

### ISSUE THREAD

**Issue by someworker** [fluttercommunity/app_review#47]
Could you please provide an example of what onValue actually is? 
Is it the rating submitted? Like onValue="5"? And if so, why is it a String?

**Comment by someworker** [comment]
Just a sanity check to make sure there were no errors. On android you could store a timestamp to know when to call again, on ios it doesnt really matter

Is not helpful. You could store means I can do something inside the function. I know that. But what does the String onValue hold?

**Comment by rodydavis** [comment]
It is not the rating that is submitted, but more for logging purposes.
