### ISSUE TITLE
SDK location not found.

### ISSUE THREAD

**Issue by HetalGohil** [fluttercommunity/app_review#50]
when i added this plugin it is giving error below:
---------------------------------------------------
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'app_review'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

Exception: The plugin app_review could not be built due to the issue above.

**Comment by fartem** [comment]
@HetalGohil What version of Gradle plugin (in `build.gradle` root file) are you using?

**Comment by alexobviously** [comment]
I'm also getting this error as of today. My project was building just fine yesterday, but it's possible that I got a new version with pub upgrade.

**Comment by rodydavis** [comment]
issue not specific to this plugin
