### ISSUE TITLE
update  package_info to ^2.0.0

### ISSUE THREAD

**Issue by erf** [fluttercommunity/app_review#52]
Please update dependency package_info: ^2.0.0

The version you now depend on ^0.5.0 causes dependency issues.

Thanks!

**Comment by karan413255** [comment]
I am also facing this issue, can it be resolved?

**Comment by erf** [comment]
I made a [fork](https://github.com/erf/app_review/tree/package_info) and a [PR](https://github.com/fluttercommunity/app_review/pull/53) for this. You can point to my `git` version to solve this. 

I would also consider the package [in_app_review](https://github.com/britannio/in_app_review) which seem more up-to-date.

**Comment by marcosmko** [comment]
Hello @rodydavis can you update this package please? There is a PR fixing this issue already!

**Comment by rodydavis** [comment]
published with `2.1.1`
