### ISSUE TITLE
Bug 2.0.1 Error: The argument type 'String' can't be assigned to the parameter type 'Uri'.

### ISSUE THREAD

**Issue by zakblacki** [fluttercommunity/app_review#54]
I'm getting this error on 2.0.1 I think it's a bug but it works fine on 1.1.2 : 

> Error: The argument type 'String' can't be assigned to the parameter type 'Uri'.
> 'Uri' is from 'dart:core'.
            .get('http://itunes.apple.com/$country/lookup?bundleId=$id')
            
here is the code I don't think it's coming from me any idea ?

     `ReviewAppDemoState pageState;

     class ReviewAppDemo extends StatefulWidget {
     @override
      ReviewAppDemoState createState() {
      pageState = ReviewAppDemoState();
      return pageState;
      }
     }

     class ReviewAppDemoState extends State<ReviewAppDemo> {
     String appID = "";
     String output = "";

    @override
     initState() {
      super.initState();
      AppReview.getAppID.then((onValue) {
       setState(() {
         appID = onValue;
       });
       print("App ID" + appID);
      });
     }

     @override
     Widget build(BuildContext context) {
     return Scaffold(
      appBar: AppBar(title: Text("Request App Review Demo")),
       body: Column(
        children: <Widget>[
          Expanded(
            child: Center(
              child: RaisedButton.icon(
                color: Colors.blueAccent,
                textColor: Colors.white,
                icon: Icon(Icons.star),
                label: Text("Review App"),
                onPressed: () {
                  rateApp();
                },
              ),
            ),
          ),
         ],
        ),
       );
      }`

**Comment by rodydavis** [comment]
fixed with published version `2.1.1`
