### ISSUE TITLE
Out of date HTTP package

### ISSUE THREAD

**Issue by nicolasvahidzein** [fluttercommunity/app_review#84]
Because XXX depends on app_review ^2.1.2+1 which depends on http ^0.13.0-nullsafety.0, http ^0.13.0-nullsafety.0 is required.
So, because zandu_mobile_admin depends on http ^1.1.0, version solving failed.
exit code 1

**Comment by toco1001** [comment]
@nicolasvahidzein 
Recommend to use [in_app_review](https://pub.dev/packages/in_app_review).

Almost same way to use.

```
import 'package:in_app_review/in_app_review.dart';

final InAppReview inAppReview = InAppReview.instance;

if (await inAppReview.isAvailable()) {
    inAppReview.requestReview();
}
```

**Comment by nicolasvahidzein** [comment]
That was my conclusion too. Thank you so much.
